"""limit_task

Revision ID: 6e2073aa7409
Revises: 226d77fa6c5a
Create Date: 2024-10-12 12:56:58.900042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2073aa7409'
down_revision: Union[str, None] = '226d77fa6c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('limit', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('count_active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'count_active')
    op.drop_column('task', 'limit')
    # ### end Alembic commands ###
